project:
  type: website
  output-dir: docs

website:
  title: "NSBM26"
  favicon: favicon.png
  navbar:
    background: "#FFFFFF"
    foreground: "#1F3A5F"
    pinned: true
    collapse: true
    search: true
    logo: "logo.png"

    left:
      - href: index.qmd
        text: Home
      - href: program.qmd
        text: Program
      - href: speakers.qmd
        text: Speakers
      - href: call.qmd
        text: Announcement
      - href: submission.qmd
        text: Submission
      - href: committee.qmd
        text: Committees
      - href: registration.qmd
        text: Registration
      - href: venue.qmd
        text: Venue
      - href: contact.qmd
        text: Contact

 
  page-footer:
    left: |
      © 2026 **NSBM26**. All rights reserved.
    center: |
      The **Microsoft CMT** service was used to manage the abstract submission and peer-review process for this seminar. This service was provided free of charge by Microsoft, including Azure cloud services, software development, and technical support.
    right: |
      Designed and maintained by the **NSBM26 Organizing Committee** using **Quarto**.

format:
  html:
    theme:
      - lux
      - custom.scss
    css: styles.css
    page-layout: full
    toc: false
    smooth-scroll: true
    anchor-sections: true
    code-copy: true
    link-external-newwindow: true

execute:
  freeze: auto